import = ["~/.config/alacritty/alacritty-theme/themes/everforest_dark_hard.toml"]



[window]
padding.x = 5
padding.y = 5
opacity = 1
blur = true
title = "pack lightly, travel far"
decorations = "Full"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 10

[cursor]
style.shape = "Beam"
style.blinking = "On"
