import = ["~/.config/alacritty/nordic.toml"]



[window]
padding.x = 5
padding.y = 5
opacity = 0.92
blur = true
#title = "pack lightly, travel far"
decorations = "Full"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 14

[cursor]
style.shape = "Beam"
style.blinking = "On"
