#!/bin/bash

iatest=$(expr index "$-" i)

## History
# Append session history instead of overwriting
shopt -s histappend
HISTSIZE=32768
HISTFILESIZE="${HISTSIZE}"
PROMPT_COMMAND='history -a'

# Update window size after each command
shopt -s checkwinsize

# Disable beep
if [[ $iatest > 0 ]]; then bind "set bell-style visible"; fi

# Color for manpages in less makes manpages a little easier to read
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# Completion
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi