# Colors
set-option -sa terminal-overrides ",xterm-256color:Tc"

# Mouse support
set -g mouse on

# Window and pane numbering to start at 1 and placed top
#set-window-option -g status-position top # Perhaps this should be bottom... or might be another good solution
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Navigate panes through ctrl + hjkl (like vim)
# This removes clear hotkey ctrl+l to clear the terminal.
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Color palette
background="default"        # Makes it transparent
foreground="#f2e6cf"
accent="#b38d59"
accent_bright="#cc9b52"
highlight="#5E81AC"
black="#121212"
border="#3d3d3d"

# Set colors to status bar
set-option -g status-style "bg=$background,fg=$foreground"
#set-option -g status-position top
set-option -g status-justify left

# Set window list styles
set-window-option -g window-status-style "bg=$background,fg=$foreground"
set-window-option -g window-status-current-style "bg=$accent,fg=$black,bold"
set-window-option -g window-status-separator " "

# Format window names in list
set-window-option -g window-status-format " #I: #W "
set-window-option -g window-status-current-format " #I: #W "

# Panes styling
set-option -g pane-border-style "fg=$border"
set-option -g pane-active-border-style "fg=$accent_bright"

# Messages
set-option -g message-style "bg=$black,fg=$foreground"

# Status bar left (session info)
set-option -g status-left "#[bg=$highlight,fg=$black,bold] #S #[bg=$background,fg=$foreground]"

# Status bar right (time and date)
set-option -g status-right "#[bg=$highlight,fg=$black,bold] @#{pane_title} "
set-option -g set-titles on
set -g set-titles-string "#T"
